packages:
  - 'packages.json' # Adjust this path to match your workspace structure
  - 'src/'     # Add other relevant paths if needed

onlyBuiltDependencies:
  - react-tsparticles
  - sharp
  - tsparticles-engine
